name: Codzienna Analiza
on:
  schedule:
    - cron: '30 15 * * *' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Pobierz kod
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Generuj raport
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: node scripts/generate.js

      - name: Zapisz i wyslij zmiany
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # 1. Dodajemy plik
          git add public/raport.json
          
          # 2. Tworzymy commit LOKALNIE
          git commit -m "Automatyczna aktualizacja raportu [skip ci]" || exit 0
          
          # 3. Pobieramy Twoje zmiany z serwera i doklejamy nasz commit na koniec
          git pull --rebase origin main
          
          # 4. Wysyłamy gotowy zestaw
          git push origin main
